version: "3.7"

services:
  base:
    container_name: base
    build:
      context: ./base
    image: ningensei848/scrap:base

# baidu:
#   container_name: baidu
#   build: 
#     context: ./baidu
#   image: ningensei848/scrap:baidu
#   # 検証用
#   # command: python3.8 /server/scrap.py >> /var/log/stdout.log 2>> /var/log/stderr.log
#   # command: ["bash", "-c", "bash /server/start_server.sh && bash"]
#   command: bash
#   # command: ["bash", "-c", "docker-entrypoint.sh"]
#   user: "${UID}:${GID}"
#   # restart: always
#   environment:
#     - DATA_VOLUME_BAIDU
#     - GOOGLE_PROFILE_PATH
#     - USER
#     - PASSWD
#   tty: true
#   volumes:
#     - ./data/baidu:/server/$DATA_VOLUME_BAIDU
#     - ./log/baidu:/server/log
#     - ./chrome:/server/chrome

  clickworker:
    container_name: cwork
    build: 
      context: ./clickworker
    image: ningensei848/scrap:cwork
    command: ["bash", "-c", "bash /server/start_server.sh && bash"]
    # command: python /server/scrap.py >> /var/log/stdout.log 2>> /var/log/stderr.log
    tty: true
    restart: always
    environment:
      - USERNAME_CWORK
      - PASS_CWORK
      - SERVICE_KEY_2CAPCHA
      - GOOGLE_SITE_KEY_CWORK
      - DATA_VOLUME_CWORK
    volumes:
      - ./data/clickworker:/server/$DATA_VOLUME_CWORK
      - ./log/clickworker:/server/log
  
  yahoo:
    container_name: yahoo
    build: 
      context: ./yahoo
    image: ningensei848/scrap:yahoo
    # command: python /server/scrap.py >> /var/log/stdout.log 2>> /var/log/stderr.log
    command: ["bash", "-c", "bash /server/start_server.sh && bash"]
    # コマンドを実行したあともコンテナが起動し続ける
    tty: true
    # このコンテナORホストマシンが再起動したときにこのコンテナを自動再起動する
    restart: always
    environment:
      - DATA_VOLUME_YAHOO
      - GOOGLE_PROFILE_PATH
    volumes:
      - ./data/yahoo:/server/$DATA_VOLUME_YAHOO
      - ./log/yahoo:/server/log
  
  mturk:
    container_name: mturk
    build: 
      context: ./mturk
    image: ningensei848/scrap:mturk
    # 検証用
    # command: python /server/scrap.py >> /var/log/stdout.log 2>> /var/log/stderr.log
    command: ["bash", "-c", "bash /server/start_server.sh && bash"]
    restart: always
    ports:
      - "8765:8765"
    environment:
      - USERNAME_MTURK
      - PASS_MTURK
      - SERVICE_KEY_2CAPCHA
      - DATA_VOLUME_MTURK
      - GOOGLE_PROFILE_PATH
    tty: true
    volumes:
      - ./data/mturk:/server/$DATA_VOLUME_MTURK
      - ./log/mturk:/server/log
      - ./chrome:$GOOGLE_PROFILE_PATH